export const environment = {
  production: true,
  abonnementUrl: 'https://paardrijvakantie.com/randmeren/API/getAboListPerYear.php?year=',
  saveVisitUrl: 'https://paardrijvakantie.com/randmeren/API/addAboDate.php',
  bootAbonnementUrl: 'https://paardrijvakantie.com/randmeren/API/getRevenuAboPerYear.php?year=',
  bootAbonnementVisitUrl: 'https://paardrijvakantie.com/randmeren/API/getAboPerDayPerYear.php?year=',
  botterListUrl: 'https://paardrijvakantie.com/randmeren/API/getBotterListPerYear.php?year=',
  botterVisitsUrl: 'https://paardrijvakantie.com/randmeren/API/getBotterVisitsPerYear.php?year=',
  botterVisitAddUrl: 'https://paardrijvakantie.com/randmeren/API/addBotterVisit.php',
  botterVisitUpdateUrl: 'https://paardrijvakantie.com/randmeren/API/updateBotterVisit.php',
  botenLijstUrl: 'https://paardrijvakantie.com/randmeren/API/getBoats.php',
  usersLijstUrl: 'https://paardrijvakantie.com/randmeren/API/getUsers.php',
  botenTypesLijstUrl: 'https://paardrijvakantie.com/randmeren/API/getBoatTypes.php',
  addOrUpdateUserBoatUrl: 'https://paardrijvakantie.com/randmeren/API/addUserBoatAbo.php',
  findBoatByUserUrl: 'https://paardrijvakantie.com/randmeren/API/findBoatByUser.php?boatid=',
};
